### ISSUE TITLE
Status & Confing

### ISSUE THREAD

**Issue by sick13** [Will565/IFI-Life-Support#5]
is it a possibility to add a "status" windows in VAB/SPH to see how much LS. is on a vessel in days

for now the only way to see is to launch the vessel and check how many days are left of LS.

Second a possibility to configure how much LS a single kerbal consumes in 24h period

that way newbies (like my self) would have the option to make IFI-LS harder or easier to manage

thx :)

**Comment by Will565** [comment]
Yes
