### ISSUE TITLE
Re-generators

### ISSUE THREAD

**Issue by sick13** [Will565/IFI-Life-Support#6]
a possibility of a new part that regenerates LS (even when on-rails) (Universal storage has a lot of neat parts)

the reason for this is simple, to stop tedious and repetitive deliveries to say a station every time LS runs low

i tried using Regolith Converter to convert Water and EC into LS (http://forum.kerbalspaceprogram.com/threads/100162-0-90-Regolith-an-open-ISRU-and-Resource-framework-0-1-2-2014-12-24)

but there is a problem with Regolith when the vessel is on rails, (inactive/out of focus vessel) the converter "does not" work in terms it does not Convert resources actively when on rails but instead  " catches up" (converts all the resources to say LS for the time it was on rails) when you go to the inactive vessel , this is no problem for short time-warps but longer timewarps are stopped and you have to return to the vessel that is running low on LS and wait till it fills up (a bit annoying)

so my proposition a new module that would work actively on rails converting the needed resources into LS (even on rails/out of focus vessels) and thus preventing undesired stops in time-warp

and of course all this if there is a will for such a thing time and if it can be done

take care :)

**Comment by Will565** [comment]
I added this as enhancement -on list to add after Configs and electric code fixes

**Comment by sick13** [comment]
cool ..also i forgot to mention there is this plugin witch might be of use for the regenerators idea i posted

http://forum.kerbalspaceprogram.com/threads/97921-Background-Processing-0-2-KSP-0-25
